version: "3.8"

services:
  django:
    build: 
      context: ./src
      dockerfile: ../Dockerfile
    container_name: django
    volumes:
      - ./src:/var/src # <-- bind the application code
      - ./static_volume:/var/src/static  # <-- bind the static files
      - ./media_volume:/var/src/media  # <-- bind the media files
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - db

  web:
    image: nginx:1.15
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./static_volume:/var/static  # <-- bind the static files again so Nginx can share volume
      - ./media_volume:/var/media  # <-- bind the media files again so Nginx can share volume
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - django
    networks:
      - nginx_network  

  db:  # <-- IMPORTANT: same name as in Djano settings.py, otherwise Django won't find the database!
    image: postgres:13.5
    container_name: database1
    env_file:  # <-- match values to Djano settings.py
      - config/db/database1_env
    networks:
      - database1_network  
    volumes:
      - ./postgres/data:/var/lib/postgresql/data # <-- bind the database to local directory

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge