# Generated by Django 3.2.10 on 2022-01-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tagtranslation_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='blog.tag'),
        ),
    ]
