# Generated by Django 3.2.10 on 2022-01-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tagtranslation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='blog.tag'),
        ),
    ]
